---
title: "TRACE NDS code for figures"
author: "Dave Costello"
date: "2025-09-26"
output: html_document
---

```{r setup, include=FALSE}
library(dplyr)
library(ggplot2)
library(ggspatial)
library(rnaturalearth)
library(cowplot)
library(terra)
```

### Load data

```{r load site data}
sites <- read.csv(file="./raw data/NDSsites.csv")
summary(factor(sites$Problem)) #60 total NDS deployments were done, 9 duplicates
unique(sites$Stream) #52 unique streams where NDS were deployed
unique(sites[sites$Problem=="None",'Stream']) #41 streams were NDS were successfully retrieved

#Streams with good NDS deployments by year
goodNDS <- sites[sites$Problem=="None",]
good21 <- goodNDS[goodNDS$Year==2021,'Stream']
good22 <- goodNDS[goodNDS$Year==2022,'Stream']
```

```{r load biomass data}
chl <- read.csv(file="./raw data/chlorophyll.csv") #Lab measured chla
BT <- read.csv(file="./raw data/benthotorch.csv") #Field fluorometry

all_algae <- merge(chl[,c(2:3,5)],BT,by=c("Sample_ID","Year"),all=T) #Combined
```

```{r load environmental data}
WQ_NDS <- read.csv(file="./raw data/WQ.csv") #Water quality samples

LULC <- read.csv(file="./raw data/LULC.csv") #Land use land cover data

NDSsoil <- read.csv(file="./raw data/soilmetalWS.csv") #Metal in soils data

#Make merged dataset - 41 streams, 99 predictors
land <- merge(LULC,NDSsoil[,c(2,4:24)],by="Stream")
landWQ <- merge(land,WQ_NDS,by.x="Stream",by.y="Site")

```


```{r load derived data}
#Classification based on presence/absence of N, P, Fe, Zn limitation
bclass <- read.csv("./derived data/classify.csv")

siteclass <- merge(sites[sites$Problem=="None",],bclass,by.x="Stream",by.y="Site",all.x=T)

#Merge classification with environmental predictors
predclass <- merge(bclass,landWQ,by.x="Site",by.y="Stream",all=T) 

#Calculated response ratios
RRchl <- read.csv("./derived data/RR_chl.csv")
RRTot <- read.csv("./derived data/RR_BT.csv")
RRdiatom <- read.csv("./derived data/RR_diatom.csv")
RRcyano <- read.csv("./derived data/RR_cyano.csv")
RRgreen <- read.csv("./derived data/RR_chlorophyte.csv")
```

```{r load models}
load("./models/rfN.Rdata")
load("./models/rfP.Rdata")
load("./models/rfFe.Rdata")

#Individual partial plots for Fe
PDP_Ndep <- partialPlot(rfFe,rfFedata,INORGNWETDEP2008WS,"Yes",n.pt=100)
PDP_P <- partialPlot(rfFe,rfFedata,SRP_ugL,"Yes",log="x",n.pt=100)

load("./models/rfZn.Rdata")

#Individual partial plot for Zn
PDP_PZn <- partialPlot(rfZn,rfZndata,SRP_ugL,"Yes",log="x") 

```


### Functions and required calculations

```{r soil maps}
#Function to convert from 3 band to one band hex color
RGBrast <- function(file){
  r <- terra::rast(file)
  
  #Extract three bands
  r_red <- r[[1]]
  r_green <- r[[2]]
  r_blue <- r[[3]]
  
  #Convert to dataframe
  rgb_df <- as.data.frame(c(r_red, r_green, r_blue), xy = TRUE)
  
  # Rename columns
  colnames(rgb_df) <- c("x", "y", "red", "green", "blue")
  
  #Create hex column
  rgb_df <- rgb_df %>%
  mutate(
    red = as.integer(red),
    green = as.integer(green),
    blue = as.integer(blue),
    hex = rgb(red, green, blue, maxColorValue = 255,alpha=127)
  )
  
  rgb_df
  }

FeAr <- RGBrast("A_Fe.tif")
ZnAr <- RGBrast("A_Zn.tif")
```

```{r log axis}
logaxis = function(minlog,maxlog,side,labels=T,scale=1){
  pow <- seq(minlog,maxlog,by=1)
  ticksat <- as.vector(sapply(pow, function(p) (1:10)*10^p))
  ifelse(labels==T,axis(side, 10^pow,las=1,cex.axis=scale),axis(side,10^pow,las=1,labels=NA,cex.axis=scale))
  axis(side, ticksat, labels=NA, tcl=-0.25, lwd=0, lwd.ticks=1)
}

```

```{r response ratio panel}
RRnames <- c("N","P","Fe","Zn","N+P","N+P+Fe","P+Fe","P+Fe+Mo","P+Fe+Ni","N+Fe","N+Fe+Zn") #Treatment names for plot
intopt <- c("Simult","Ind add","Ind sub","Ind sup") #Options for what we consider co-limitation

#Function to make the response ratio plots. Data must be in format produced in statistics.Rmd
RRplot <- function(RRdata,xmin=-1,xmax=3){ 
  par(pty="m",mar=c(4,5,2,2))
  
  #Build structure of plot and axes
  stripchart(RRdata[,3:13],pch=1,cex=0,las=1,xlim=c(xmin,xmax),ylim=c(0.5,11.5),
             xlab="ln response ratio",group.names = rev(RRnames))
  
  #Bounding box based on Harpole et al. 2011 thresholds
  rect(-0.326,0,0.326,15,col="grey90",border=NA)
  abline(v=0)
  
  #Add single element treatments
  for(i in 1:4){points(RRdata[,2+i],11-i+jitter(rep(1,41),factor=5),cex=1.5,
                     col=ifelse(RRdata[,2+i]>0.326,"royalblue","gray30"))}
  
  text(xmax,11.4,"SINGLE LIMIT",adj=1)
  
  #Add text showing the # of limited streams/total streams
  for(i in 3:6){text(xmax,(11:8)[i-2],paste(sum(RRdata[,i]>0.326 ,na.rm=T),
                                  "/",sum(!is.na(RRdata[,i])),sep=""),adj=1)}
  
  #Add points for multiple element treatments 
  for(i in c(1:5,7)){points(RRdata[,6+i],7-i+jitter(rep(1,41),factor=5),cex=1.5,
                     col=ifelse(RRdata[,20+i] %in% intopt,"goldenrod2","gray30")
                     )}
  #Only did NxFe for 2022 - add seperately
  with(RRchl[RRdata$Site %in% good22,],
             points(NFe,1+jitter(rep(1,14),factor=5),cex=1.5,
                     col=ifelse(NxFecl %in% intopt,"goldenrod2","gray30")
                    ))
  
  text(xmax,7.4,"CO-LIMIT",adj=1)
  
  #Add text showing the # of co-limited streams/total streams
  for(i in 21:27){text(xmax,(7:1)[i-20],paste(sum(RRdata[,i] %in%
                  intopt,na.rm=T), "/",sum(!is.na(RRdata[,i])),sep=""),adj=1)}
}

```


### Code for figures 

```{r Figure 1 - Maps}
states <- ne_states(country=c("united states of america","canada"),returnclass="sf")

maplim <- function(limvar,limcol,legname,bgmap=NULL){
  
  #set colors for points and legend
  colno <- which(colnames(siteclass)==limvar)
  
  legend_data <- data.frame(percentile = rev(c("90-100", "80-90", "70-80", "60-70", "50-60","40-50", "30-40", "20-30", "10-20", "0 -10")),
  fill = rev(c("#FF0000", "#FF7F00", "#FFFF00", "#ADFF2F", "#7FFF7F",
               "#66FFCC", "#33CCFF", "#3399FF", "#3366FF", "#0000FF")),
  y = 1:10,alpha=rep(127,10))
  
            #Map with no background raster
    if(is.null(bgmap)){
      ggplot() + 
        geom_sf(data = states,fill="antiquewhite") +
 
        #Add open circles at all sites
        geom_point(data=siteclass,
               mapping=aes(y=Latitude,x=Longitude),
               color="grey30",size=3,pch=1,stroke=1.5)+
  
        #Overlay colors points for sites limited by nutrient
        geom_point(data=siteclass[siteclass[,colno]=="Yes",],
               mapping=aes(y=Latitude,x=Longitude),colour=limcol,size=3)+
        
        #Build legend
        geom_rect(aes(xmin=-84,xmax=Inf,ymin=47,ymax=Inf),
            fill="white",color="grey30")+
        geom_point(aes(x=-83,y=48),colour=limcol,size=3)+
        annotate("text",x=-80,y=48,label=paste(legname,"limited"))+
        
        #Map limits
        coord_sf(xlim = c(-90, -78), ylim = c(30, 48))+
        
        #Add scale bar
        annotation_scale(location = "br", width_hint = 0.3) + 
    
        #Add north arrow
        annotation_north_arrow(location = "br", which_north = "true", 
                               pad_y = unit(0.2, "in"),pad_x = unit(0,"in"),
                               height = unit(0.5,"in"), style = 
                               north_arrow_fancy_orienteering) +
        
        #Theme
        theme(panel.background = element_rect(fill = "aliceblue"),
        panel.border = element_rect(colour = "black", fill=NA,linewidth=1),
        axis.title.x=element_blank(),axis.title.y=element_blank(),
        axis.text.x=element_text(angle=90),
        panel.grid.major = element_blank())}
  
            #Map with background raster
    else{
      ggplot() + 
        geom_sf(data = states,fill="antiquewhite") +
        
        #Add soil raster
        geom_raster(data=bgmap,mapping=aes(y=y,x=x,fill=hex))+
        
        #Remove legend
        scale_fill_identity(guide = "none") +
        
        #Add open circles at all sites
        geom_point(data=siteclass,
               mapping=aes(y=Latitude,x=Longitude),
               color="grey30",size=3,pch=1,stroke=1.5)+
        
        #Overlay colors points for sites limited by nutrient
        geom_point(data=siteclass[siteclass[,colno]=="Yes",],
               mapping=aes(y=Latitude,x=Longitude),colour=limcol,
             size=3)+
        
        #Build legend
        geom_rect(aes(xmin=-84,xmax=Inf,ymin=47,ymax=Inf),
                  fill="white",color="grey30")+
        geom_point(aes(x=-83,y=48),colour=limcol,size=3)+
        annotate("text",x=-80,y=48,label=paste(legname,"limited"))+
        
        #Map limits
        coord_sf(xlim = c(-90, -78), ylim = c(30, 48))+
        
        #Add scale bar
        annotation_scale(location = "br", width_hint = 0.3) +
        
        #Add north arrow
        annotation_north_arrow(location = "br", which_north = "true", 
                               pad_y = unit(0.2, "in"),pad_x = unit(0,"in"),
                               height = unit(0.5,"in"), style =
                               north_arrow_fancy_orienteering) +
        
        #Add raster legend
        geom_rect(aes(xmin=-Inf,xmax=-87.6,ymin=-Inf,ymax=33),
                  fill="white",color="grey30")+
        annotate("text",x=-89,y=32.8,label="Percentile",size=2,fontface=2)+
        geom_tile(data = legend_data, aes(x = -90, y = (y*0.32)+29.2, 
                  fill = fill), width = 0.8) +
        geom_text(data = legend_data, aes(x = -89.5, y = (y*0.32)+29.2,
                  label = percentile), hjust = 0, size = 2) +
        
        #Theme
        theme(panel.background = element_rect(fill = "aliceblue"),
        panel.border = element_rect(colour = "black", fill=NA, linewidth=1),
        axis.title.x=element_blank(),axis.title.y=element_blank(),
        axis.text.x=element_text(angle=90),
        panel.grid.major = element_blank())
  }
}

plot_grid(
  maplim("N_TF","green3","N"),
  maplim("P_TF","dodgerblue2","P"),
  maplim('Fe_TF',"orangered","Fe",bgmap=FeAr),
  maplim('Zn_TF',"purple3","Zn",bgmap=ZnAr),
nrow=1,labels = "auto"
  )

```

```{r Figure 2 - Chla response}
RRplot(RRchl,xmin=-1,xmax=4)
```

```{r Figure 3 - Community response}
RRplot(RRTot,xmax=4) #(a) Total BenthoTorch biomass 
RRplot(RRdiatom,xmax=4) #(b) Diatom biomass 
RRplot(RRcyano,xmax=4) #(c) Cyanobacteria biomass 
RRplot(RRgreen,xmin=-4,xmax=6) #(d) Chlorophyte biomass
```

```{r Figure 4 - Iron RF model}
layout(matrix(c(2,1,1,1, 2,1,1,1, 2,1,1,1, 0,3,3,3),4,4))

#Main scatterplot
par(mai=c(0.6,0.6,0,0))
plot(INORGNWETDEP2008WS~SRP_ugL,data=rfFedata,log="x",col=c("orangered","black")[Fe_TF],xlim=c(1,100),ylim=c(2,8),las=1,pch=c(16,1)[Fe_TF],
     xlab="DRP concentration (µg/L)",
     ylab="Inorganic N wet deposition (kg N/ha/yr)",cex=1.8,xaxt="n",cex.lab=1.2)
text(1,8,"a",cex=2)
logaxis(0,3,1)
legend("topright",legend=c("Fe limited","Not Fe limited"),pch=c(16,1),col=c("orangered","black"),pt.cex=1.8)
abline(h=3.55,lty=2)
abline(v=5.57,lty=2)

#Partial dependency for DRP
par(mai=c(0.2,0.6,0.2,0))
plot(PDP_P$y~PDP_P$x,type="l",log="x",xlim=c(1,100),xaxt="n",las=1,
     xlab="",ylim=c(-0.2,0.5),ylab="logit(Fe)",cex.lab=1.2)
text(1,0.85,"b",cex=2)
logaxis(0,3,1,labels=F)
text(13,c(0.16,0.04),c("Probable","Fe limitation"),col="orangered")
abline(v=5.57,lty=2)

#Partial dependency for N dep
par(mai=c(0.6,0.2,0,0.2))
plot(PDP_Ndep$x~PDP_Ndep$y,type="l",ylim=c(2,8),yaxt="n",las=1,
     ylab="",xlim=c(-0.5,0.5),xlab="logit(Fe)",cex.lab=1.2)
text(-0.4,8,"c",cex=2)
text(0,c(3.12,2.88),c("Probable","Fe limitation"),col="orangered")
axis(2,labels=F)
#mtext("-0.5",1,line=1,at=-0.5,cex=2/3)
abline(h=3.55,lty=2)
```

```{r Figure 5 - Zinc RF model}
#Partial dependency for DRP
plot(PDP_PZn$y~PDP_PZn$x,type="l",xlim=c(1,100),xaxt="n",las=1,
     xlab="DRP concentration (µg/L)",ylim=c(-0.7,0.1),
     ylab="logit(Zn)",cex.lab=1.2,log="x")
logaxis(0,2,1)

#Overlay stripchart
stripchart(rfZndata[rfZndata$Zn_TF=="No",'SRP_ugL'],col="black",
           pch=1,at=-0.3,add=T,method = "jitter",cex=1.2,jitter = 0.1)
stripchart(rfZndata[rfZndata$Zn_TF=="Yes",'SRP_ugL'],col="purple3",
           pch=16,at=-0.3,add=T,method = "jitter",cex=1.2,jitter=0.1)


legend("bottomright",legend=c("Zn limited","Not Zn limited"),pch=c(16,1),col=c("purple3","black"),pt.cex=1.2)

```

```{r Figure S3 - field v lab biomass}
#Linear model
mod1<- lm(log10(Total)~log10(CHLA)*Year,data=all_algae)
summary(mod1) #Difference in slope between 2021 and 2022. Greater slope in 2022

#Best-fit line for arithmetic plot
predchl <- seq(1,100,by=1)
pred21 <- predict(mod1,data.frame(Year=rep(2021,100),CHLA=predchl))
pred22 <- predict(mod1,data.frame(Year=rep(2022,100),CHLA=predchl))

#Code for plot S3
plot(Total~CHLA,data=all_algae[all_algae$Year==2021,],col="red",pch=16,las=1,
     xlim=c(0,100),ylim=c(0,10),
     xlab=expression(paste("Lab-measured chlorophyll ",italic(a), " (µg/cm"^2*")")),
     ylab=expression(paste("Field-measured chlorophyll ",italic(a), " (µg/cm"^2*")")))
points(Total~CHLA,data=all_algae[all_algae$Year==2022,],col="dodgerblue",pch=1)
legend("bottomright",c("2021","2022"),col=c("red","dodgerblue"),
       pch=c(16,1),lty=c(1,2))
lines(predchl,10^pred21,col="red")
lines(predchl,10^pred22,col="dodgerblue",lty=2)
text(80,10,"r-squared = 0.58")
```

```{r Figure S4 - RF top 10 vars}
varImpPlot(rfZn,n.var=10)

#Function to trim importance variables
clipimp <- function(model,var.no){
  impdf<- data.frame("Gini" = importance(model),
                     "Variable"=row.names(importance(model)))
  impdf2 <- impdf[order(impdf$MeanDecreaseGini,decreasing=T),]
  clipdf <- impdf2[1:var.no,]
  clipdf
  }

#Generate top 10 importance for each response
NI <- clipimp(rfN,10)
PI <- clipimp(rfP,10)
FeI <- clipimp(rfFe,10)
ZnI <- clipimp(rfZn,10)

#Clean variable names
NIvar <- c("WS area",
            expression("Stream NO"[3]),
            "WS forest",
            "Stream TN",
            "WS soil OM",
            "Stream TP",
            "WS septic",
            "WS air temp.",
            expression("WS soil Fe"[2]*"O"[3]),
            "WS mid urban")

PIvar <- c("Stream Co",
           "WS soil CaO",
           expression("WS soil P"[2]*"O"[5]),
           "WS soil perm,",
           "Stream DRP",
           "WS precip.",
           "Stream TP:Fe",
           "WS soil S",
           "WS soil N",
           expression("WS soil K"[2]*"O")
           )

FeIvar <- c(expression("WS N"[DEP]),
            "Stream DRP",
           "Stream Mo",
           "WS area",
           "Stream TP:Fe",
           "WS deciduous",
           "WS soil MgO",
           "WS soil CaO",
           "A hor. Zn",
           "Stream pH"
           )

ZnIvar <- c("Stream DRP",
            "Stream Co",
            "WS soil CaO",
            "WS anthro. N",
            "WS N surplus",
            expression(paste("Control chl",italic("a"))),
            "Stream TN:Fe",
            "Stream Mn",
            expression("Stream NH"[4]),
            expression("WS soil K"[2]*"O")
            )

#Function to create importance plot
ImpPlot <- function(Idf,Ivar,panelname){
  plot(rev(Idf$MeanDecreaseGini),seq(1,dim(Idf)[1]),cex=1.5,
     yaxt="n",xlab="Mean decrease in Gini impurity",ylab="")
  mtext(Ivar,at=seq(dim(Idf)[1],1),side=2,las=1,line=0.5)
  text(min(Idf$MeanDecreaseGini),dim(Idf)[1],panelname,cex=1.5,adj=0)
}

#Final plots
par(mfrow=c(2,2),mar=c(4,8,1,1))

ImpPlot(NI,NIvar,"a. Nitrogen")
ImpPlot(PI,PIvar,"b. Phosphorus")
ImpPlot(FeI,FeIvar,"c. Iron")
ImpPlot(ZnI,ZnIvar,"d. Zinc")
```

